# roles/docker/handlers/main.yml
- name: Restart Docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
    daemon_reload: true

- name: Restart Auditd
  ansible.builtin.service:
    name: auditd
    state: restarted
