# inventories/production/hosts.yml
# Production inventory for SummitEthic infrastructure
# Ethical principle: Clear documentation of all systems

all:
  vars:
    # --- Global variables ---
    ansible_user: ansible
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_python_interpreter: /usr/bin/python3
    environment: production

    # --- Ethical configuration ---
    enable_audit_logging: true
    enable_encryption: true
    enable_privacy_protection: true

    # --- SSH hardening ---
    ssh_port: 22
    ssh_permit_root_login: "no"
    ssh_password_authentication: "no"
    ssh_pubkey_authentication: "yes"

    # --- Firewall configuration ---
    ufw_enabled: true
    ufw_rules:
      - { rule: allow, port: 22, proto: tcp, comment: "SSH" }
      - { rule: allow, port: 80, proto: tcp, comment: "HTTP" }
      - { rule: allow, port: 443, proto: tcp, comment: "HTTPS" }
      - { rule: allow, port: 25, proto: tcp, comment: "SMTP" }
      - { rule: allow, port: 587, proto: tcp, comment: "SMTP Submission" }
      - { rule: allow, port: 993, proto: tcp, comment: "IMAPS" }
      - { rule: allow, port: 995, proto: tcp, comment: "POP3S" }

    # --- Docker configuration ---
    docker_users:
      - ansible
    docker_daemon_options:
      log-driver: "json-file"
      log-opts:
        max-size: "10m"
        max-file: "3"

    # --- Backup configuration ---
    backup_enabled: true
    backup_schedule: "0 2 * * *"  # 2 AM daily
    backup_retention_days: 30
    backup_destinations:
      - local: /opt/summitethic/backups
      - remote: "{{ vault_backup_remote_destination }}"

  children:
    webservers:
      hosts:
        summitethic-prod:
          ansible_host: "{{ vault_production_server_ip }}"
          ansible_port: 22

          # Server specific configurations
          server_role: primary
          datacenter: contabo-de

          # Domain configuration
          domain_name: summitethic.com
          subdomain_configs:
            - { name: www, type: A, target: "{{ ansible_host }}" }
            - { name: git, type: CNAME, target: summitethic.com }
            - { name: mail, type: CNAME, target: summitethic.com }
            - { name: marketing, type: CNAME, target: summitethic.com }
            - { name: dashboard, type: CNAME, target: summitethic.com }
            - { name: metrics, type: CNAME, target: summitethic.com }
            - { name: traefik, type: CNAME, target: summitethic.com }

          # Service configurations
          services:
            - { name: traefik, enabled: true, ports: [80, 443, 8080] }
            - { name: gitlab, enabled: true, subdomain: git, resources: { memory: 4G, cpu: 2 } }
            - { name: mailcow, enabled: true, subdomain: mail, resources: { memory: 2G, cpu: 1 } }
            - { name: mautic, enabled: true, subdomain: marketing, resources: { memory: 2G, cpu: 1 } }
            - { name: wordpress, enabled: true, subdomain: www, resources: { memory: 1G, cpu: 0.5 } }
            - { name: matomo, enabled: true, subdomain: analytics, resources: { memory: 1G, cpu: 0.5 } }
            - { name: monitoring, enabled: true, components: [prometheus, grafana, loki, alertmanager] }

    monitoring:
      hosts:
        summitethic-prod:
          # Monitoring specific variables
          prometheus_retention_days: 30
          grafana_admin_user: admin
          alerting_enabled: true

    databases:
      hosts:
        summitethic-prod:
          # Database configurations
          postgresql_version: 15
          postgresql_max_connections: 200
          postgresql_shared_buffers: 256MB

    mailservers:
      hosts:
        summitethic-prod:
          # Mail server configurations
          mail_domain: summitethic.com
          dkim_enabled: true
          spf_enabled: true
          dmarc_enabled: true
