---
# roles/traefik/handlers/main.yml
- name: Restart Traefik
  docker_compose:
    project_src: /opt/traefik
    restarted: true
    services:
      - traefik

- name: Reload Traefik
  docker_container:
    name: traefik
    restart: true
