---
# roles/traefik/handlers/main.yml
- name: Restart Traefik
  community.docker.docker_compose_v2:
    project_src: /opt/traefik
    restarted: true
    services:
      - traefik

- name: Reload Traefik
  community.docker.docker_container:
    name: traefik
    restart: true
