---
# roles/traefik/tasks/main.yml
# Traefik setup with automatic SSL and security features

- name: Create Traefik directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: docker
    mode: '0750'
  loop:
    - /opt/traefik
    - /opt/traefik/configs
    - /opt/traefik/certs
    - /opt/traefik/logs

- name: Generate Traefik dashboard password
  htpasswd:
    path: /opt/traefik/.htpasswd
    name: "{{ traefik_dashboard_user | default('admin') }}"
    password: "{{ traefik_dashboard_password }}"
    owner: root
    group: docker
    mode: '0640'

- name: Deploy Traefik static configuration
  template:
    src: traefik.yml.j2
    dest: /opt/traefik/traefik.yml
    owner: root
    group: docker
    mode: '0640'
  notify: restart traefik

- name: Deploy Traefik dynamic configurations
  template:
    src: "{{ item }}.j2"
    dest: "/opt/traefik/configs/{{ item }}"
    owner: root
    group: docker
    mode: '0640'
  loop:
    - middlewares.yml
    - routers.yml
    - services.yml
    - tls.yml
  notify: reload traefik

- name: Create acme.json for Let's Encrypt certificates
  file:
    path: /opt/traefik/certs/acme.json
    state: touch
    owner: root
    group: docker
    mode: '0600'
    modification_time: preserve
    access_time: preserve

- name: Deploy Traefik docker-compose
  template:
    src: docker-compose.yml.j2
    dest: /opt/traefik/docker-compose.yml
    owner: root
    group: docker
    mode: '0640'

- name: Start Traefik container
  docker_compose:
    project_src: /opt/traefik
    state: present
    pull: yes
    recreate: smart

- name: Wait for Traefik to be ready
  uri:
    url: "http://localhost:8080/api/rawdata"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 30
  delay: 10